title: Defy
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://zladnrms.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: zladnrms
   twitter: zladnrms
   facebook: zladnrms
   email: zladnrms111@gmail.com

google_analytics: "UA-58263416-1"
